language: node_js
node_js:
- '12'
cache:
  yarn: true
deploy:
  provider: npm
  email: axyzxp@gmail.com
  api_key:
    secure: Ki8MFhTiq0c744sicpv9tUzYURDZhIVx2U0mXTUUudSkaRCIzY69qjkbTOElFhgbw/A0G4bA1L7hTDrNOpaFb8PANKLK6qWgHI9PkkPrsycIf+5IkuNYhXEznMpFHdawndMlKf32McTFxZXdG9TisrDHWcjLrhWIEUIXY4AJ1bd8zWpKF6q+kSemjrH3y2BJfJceY58ZaJr22ZQo9ngMAkMbmKBMnFqrQlMYcKtCBabni/EP9Xj7HXzAqFeSJNn6UQHu1XtZN9wXzHafL9IMsFlR/ZKU0mbVGEzj0bqV6CtC2/3XwHFy1iIgwhIFJ1YGGc3OiwoXkJ/XSBTjMqgWtsR2CUV7bO/KEcLQiPza5TOZ/AKR4rgmkNBHxDgRHTwgZgCExZ/YmpXX8y9StHVUBF8msxipESeLx/OBhvlbxRYgnoZzwjkOK2+OBS+TznRlWnGc0XkItSRt7VvgDWFO7RWnbFx22Xd/bnhC1L33i5nEH8JhMLehOnJmybIuY01/x49waA5ReqgAqDENumGUdl/jThF1elATslgQyMEzAk8/KGwBb79+tHcrQzWwAFEFtC96T5lGmnt3zVhZhs6qriwLd4kqvfHzcsGx/RrXIDqZjNFpFYML8kU1U+9aIQoCLg7zl6Cwr57YTW+/iu58YpWk3TJzHETnueKJPP9h5Ho=
  skip_cleanup: true
  on:
    tags: true
    repo: utilitycss/extract-used-atoms-webpack-plugin
